code_build_name = 'PersonalWebsiteUI'
role_name = 'PersonalWebsiteUIBuildRole'
profile_name = 'PersonalWebsiteUIBuildProfile'
policy_name = 'PersonalWebsiteUIBuildPolicy'
docker_image = 'nplutt/headless-chrome-ubuntu'
repo_url = 'https://github.com/nplutt/personal-website.git'
